#**why numby?!**

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types.

##**Data types  section**

Datatypes

In [ ]:
dtypes = pd.DataFrame(
    {
        'Type': [
            'int8', 
            'uint8', 
            'int16', 
            'uint16', 
            'int or int32', 
            'uint32', 
            'int64', 
            'uint64', 
            'float16', 
            'float32', 
            'float or float64',
            'float128', 
            'complex64', 
            'complex or complex128', 
            'bool', 
            'object', 
            'string_',
            'unicode_',
        ],
        
        'Type Code': [
            'i1', 
            'u1', 
            'i2', 
            'u2', 
            'i4 or i', 
            'u4', 
            'i8', 
            'u8', 
            'f2', 
            'f4 or f', 
            'f8 or d', 
            'f16 or g', 
            'c8', 
            'c16', 
            None, 
            'O', 
            'S', 
            'U',
        ]
    }
)

dtypes

Type Type Code
0                    int8        i1
1                   uint8        u1
2                   int16        i2
3                  uint16        u2
4            int or int32   i4 or i
5                  uint32        u4
6                   int64        i8
7                  uint64        u8
8                 float16        f2
9                 float32   f4 or f
10       float or float64   f8 or d
11               float128  f16 or g
12              complex64        c8
13  complex or complex128       c16
14                   bool      None
15                 object         O
16                string_         S
17               unicode_         U

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5]) #Crerating an array
print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.array([1,2,3], dtype='f4') #Creating an array with with type float f4 is type code 
arr.dtype 
#you can use np.(dataType)
#arr = np.array([1+2j, 3-4j],dtype=np.float32)
#arr.dtype 


dtype('float32')

**Notice**

arr = np.array([1+2j, 3-4j], dtype=np.complex64)

arr.dtype

arr = np.array([1+2j, 3-4j], dtype='c8')

arr.dtype

the output of the above code is same **dtype('complex64')**


arr = np.array([1+2j, 3-4j], dtype=np.c8)

arr.dtype

output of this code is 

**ُERROR (AttributeError: module 'numpy' has no attribute 'c8'**)

**Type Conversion**

astype method: convert the data type of an array to other data types.

Notice 

that astype returns a copy of the array instead of converting the data type in place. You need to assign the copy to the original array or a new array.

In [ ]:
arr = np.array([1,2,3], dtype=np.int16)
print(arr.dtype)

arr = arr.astype(np.float32)
print('Data Type After Conversion: ' + str(arr.dtype)) 
arr

int16
Data Type After Conversion: float32


array([1., 2., 3.], dtype=float32)

In [ ]:
#WARNING: be cautious about data overflow when you downcast the data type
#(from higher precision to lower precision). 
#Some unexpected and undefined values might occur and it is usually difficult to debug such issues.



# An example of integer overflow at downcasting
arr = np.array([126,127,256], dtype='int16')
print('np array before type conversion: ' + str(arr))

# Range of int8 [-128, 127], 256 overflows after conversion
arr = arr.astype('int8')
print('np array after type conversion: ' + str(arr))


#overflow الملخص انه حصل
#عشان حولنا من 
#int8 ل int16

np array before type conversion: [126 127 256]
np array after type conversion: [126 127   0]


String and Unicode Data Type

The string_ and unicode_ data types are all implicitly fixed-length.

The length of the string is given by their type code appended with a number. 

For example, S3 represents string of length 3; U10 represents unicode of length 10. Otherwise, the default length is the length of the longest string in the array.

If the length of a string in the array is shorter than the length of the data type defined or converted to, the string will be truncated.

In [ ]:
# An example of truncated string
s = np.array(['abc', 'defg'], dtype='S4')
print(s)

# An example of truncated unicode
s = np.array(['abcd', 'efghi'], dtype='U')
print(s)

[b'abc' b'defg']
['abcd' 'efghi']


In [ ]:
arr = np.array(['a', 'ab', 'abc'], dtype=np.string_)
print('The array is ' + str(arr))
print('The data type is ' + str(arr.dtype) + ' because the longest string in the array is "abc" and its length is 3.')

arr = np.array(['a', 'abc', 'abcd'], dtype=np.unicode_)
print('The array is ' + str(arr))
print('The data type is ' + str(arr.dtype) + ' because the longest unicode in the array is "abcd" and its length is 4.')


The array is [b'a' b'ab' b'abc']
The data type is |S3 because the longest string in the array is "abc" and its length is 3.
The array is ['a' 'abc' 'abcd']
The data type is <U4 because the longest unicode in the array is "abcd" and its length is 4.


##**Array section**

Create an array from an iterable
Such as

list

tuple

range iterator

**Notice** that not all iterables can be used to create a numpy array, such as **set** and **dict**

**Notice**

**List []**
1.   List items are ordered(**If you add new items to a list, the new items will be placed at the end of the list.**).
2.   changeable(**The list is changeable, meaning that we can change, add, and remove items in a list after it has been created**.).
3. Allow duplicate values.



**Set {}**

1.  Unordered
2.  Unchangeable
3.Duplicates Not Allowed



**Tuple ()**



1.   Ordered
2.   Unchangeable
3.   Allow Duplicates


Dictionary{Key:value}

     **1-Order**

       As of Python version 3.7, dictionaries are ordered. In Python 3.6 and    earlier, dictionaries are unordered.

     **2-changeable**

     **3-Duplicates Not Allowed**

     Dictionaries cannot have two items with the same key

  







              





In [ ]:
#Examples
arr = np.array([1,2,3,4,5])
print(arr)
arr = np.array((1,2,3,4,5))
print(arr)
arr = np.array(range(10))
print(arr)

[1 2 3 4 5]
[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.array([1,2,3], dtype='f4') #Creating an array with with type float f4 is type code 
print(arr)
print('Data Type: ' + str(arr.dtype))
#you can use np.(dataType)

[1. 2. 3.]
Data Type: float32


In [ ]:
# np.arange(start, stop, step)
arr = np.arange(0, 21, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


 **Create an array of evenly spaced numbers within specified range**

np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False) has 5 parameters:

start: start number (inclusive)

stop: end number (inclusive unless endpoint set to False)

num_of_elements: number of elements contained in the array

endpoint: boolean value representing whether the stop number is inclusive or not

retstep: boolean value representing whether to return the step size





In [ ]:
arr, step_size = np.linspace(0, 5, 8, endpoint=False, retstep=True)
print(arr)
print('The step size is ' + str(step_size))

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375]
The step size is 0.625


In [ ]:
arr = np.linspace(0, 5, 8, endpoint=True, retstep=False)
print(arr)


[0.         0.71428571 1.42857143 2.14285714 2.85714286 3.57142857
 4.28571429 5.        ]


Create an array of random values of given shape

np.random.rand() method returns values in the range [0,1)

In [ ]:
arr = np.random.rand(3,4)
print(arr)

[[0.28868831 0.87481845 0.5985185  0.03488039]
 [0.39544388 0.48465798 0.9914372  0.3235997 ]
 [0.11472229 0.10622935 0.81384408 0.04216096]]


 **Create an array of zeros of given shape**

**np.zeros()**: create array of all zeros in given shape

**np.zeros_like()**: create array of all zeros with the same shape 

and data type as the given input array

**Create an array of ones of given shape**

**np.ones()**: create array of all ones in given shape

**np.ones_like()**: create array of all ones with the same shape and data type as the given input array


In [ ]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.int16)
zeros = np.zeros_like(arr)
print(zeros)
print('Data Type: ' + str(zeros.dtype))

[[0 0]
 [0 0]
 [0 0]]
Data Type: int16


**Create an empty array of given shape**

**np.empty()**: create array of empty values in given shape

**np.empty_like()**: create array of empty values with the same shape and data type as the given input array

**Notice**

that the initial values are not necessarily set to zeroes.

They are just some garbage values in random memory addresses 

In [ ]:
empty = np.empty((5,5))
print(empty)

print("---------------------------------------------------------")

arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
empty = np.empty_like(arr)
print(empty)
print('Data Type: ' + str(empty.dtype))

[[4.67639118e-310 7.60861095e-322 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [1.16095484e-028 2.17237198e-153 4.83245960e+276 8.97600980e-096
  3.77075671e+233]
 [1.96087885e+243 2.92158436e-014 2.59345444e+161 3.42703236e-062
  4.07175424e+223]
 [9.15279752e+242 2.20132022e-152 1.96088859e+243 3.03837572e+180
  3.77075632e+233]
 [1.96087885e+243 6.32672800e+180 4.74483502e+170 4.59210323e-072
  1.58357921e-319]]
---------------------------------------------------------
[[1065353216 1073741824 1077936128]
 [1082130432 1084227584 1086324736]]
Data Type: int64


**Create an array of constant values of given shape**

**np.full()**: create array of constant values in given shape

**np.full_like()**: create array of constant values with the same shape and data type as the given input array

In [ ]:
full = np.full((4,4), 5)
print(full)

print("---------------------------------------------------------")

arr = np.array([[1,2], [3,4]], dtype=np.float64)
full = np.full_like(arr, 5)
print(full)
print('Data Type: ' + str(full.dtype))

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
---------------------------------------------------------
[[5. 5.]
 [5. 5.]]
Data Type: float64


**Create an array in a repetitive manner**

np.repeat(iterable, reps, axis=None): repeat each element by n times

iterable: input array

reps: number of repetitions

axis: which axis to repeat along, default is None which will flatten the input array and then repeat

np.tile(): repeat the whole array by n times

iterable: input array

reps: number of repetitions, it can be a tuple to represent repetitions along x-axis and y-axis

In [ ]:
# No axis specified, then flatten the input array first and repeat
# Data Augemnation 
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 4)) 

[0 0 0 0 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5]


In [ ]:
# An example of repeating along x-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=0)) 

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [ ]:
# An example of repeating along y-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=1)) 

[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


In [ ]:
# Repeat the whole array by a specified number of times
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [ ]:
# Repeat along specified axes
print(np.tile(arr, (2,2)))

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


**Create an identity matrix of given size**

**np.eye(size, k=0)**: create an identity matrix of given size
**size**: the size of the identity matrix

**k**: the diagonal offset

**np.identity()**: same as np.eye() but does not carry parameters

In [ ]:
identity_matrix = np.eye(5)
identity_matrix.astype(int)
print(identity_matrix)
print('\n')
# An example of diagonal offset# 
identity_matrix = np.eye(5, k=-1)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [ ]:
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


 **Create an array with given values on the diagonal**

In [ ]:
arr = np.random.rand(5,5)
print(arr)
print('\n')
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.70505533 0.85329318 0.08177551 0.48546015 0.82661768]
 [0.56217222 0.37876538 0.90388452 0.84965428 0.71288134]
 [0.04556548 0.30508785 0.01444309 0.67948788 0.6452963 ]
 [0.08595185 0.94783298 0.60289772 0.49307462 0.73881069]
 [0.65278209 0.24715355 0.55658169 0.84598208 0.55948206]]


Values on the diagonal: [0.70505533 0.37876538 0.01444309 0.49307462 0.55948206]


In [ ]:
# Create a matrix given values on the diagonal
# All non-diagonal values set to zeros
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


##**Inspect an Array section**





In [ ]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)

**inspect general information of an array**

In [ ]:
print(np.info(arr))
#class:  ndarray  
#shape:  (2, 3) 
#strides:  (24, 8)
#itemsize:  8
#aligned:  True
#contiguous:  True
#fortran:  False
#data pointer: 0x25cec286150
#byteorder:  little
#byteswap:  False
#type: int64
#None

None


In [ ]:
#inspect the dimension of an array
print(arr.shape[1])

3


In [ ]:
#inspect the data type of an array
print(arr.dtype)

int64


In [ ]:
#inspect length of an array
print(len(arr))

2


In [ ]:
#inspect the number of dimensions of an array
print(arr.ndim)

2


In [ ]:
#inspect the number of elements in an array
print(arr.size)

6


In [ ]:
#inspect the number of bytes of each element in an array
print(arr.itemsize)

8


In [ ]:
# arr.nbytes = arr.size * arr.itemsize
print(arr.nbytes)

48


#**Sampling Methods section**

In [ ]:
np.random.seed(123)#random بتثبت الرقم ال 
#بتسبش البركت فاضي 
np.random.rand(3)


array([0.69646919, 0.28613933, 0.22685145])

In [ ]:
rs = np.random.RandomState(123) #random بتثبت الرقم ال
# rsفي المتغير الي اسمه 
rs.rand(10)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897,
       0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752])

**generate a random sample from interval [0, 1) in a given shape**

In [ ]:
# generate a random scalar
print(np.random.rand())    #generate  random variables 
 

0.42310646012446096


In [ ]:
# generate a 1-D array
print(np.random.rand(3))   

[0.73799541 0.18249173 0.17545176]


In [ ]:
# generate a 2-D array
print(np.random.rand(3,3)) 

[[0.53155137 0.53182759 0.63440096]
 [0.84943179 0.72445532 0.61102351]
 [0.72244338 0.32295891 0.36178866]]


In [ ]:
print(np.random.randn(3,3))#generate random numbers may includes -Ve numbers

[[-0.74765132 -0.98486761 -0.74856868]
 [ 0.24036728 -1.85563747 -1.7794548 ]
 [-2.75022426 -0.23415755 -0.69598118]]


enerate an array of random integers in a given interval [low, high)

In [ ]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[5 7 4]


generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [ ]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(3))
print('\n')
print(np.random.random(3))
print('\n')
print(np.random.ranf(3))
print('\n')
print(np.random.sample(3))

[0.99261363 0.40518518 0.19017372]


[0.48817449 0.50236965 0.40335482]


[0.18109542 0.0480298  0.60469135]


[0.26591121 0.881347   0.58404612]


generate a random sample from a given 1-D array

In [ ]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.8, 0.1]))#p ديه معناها الاحتماليات الي انت عايز الارقام تطلع بيها

[1 1 1 2 1 2 2 0 1 1]


In [ ]:
print(np.random.choice([1,2,3], 10))

[3 3 1 3 2 1 2 1 2 3]


In [ ]:
print(np.random.choice(3, 10))

[2 2 2 2 2 1 0 0 1 1]


 **If  a given  array is more than 1-D then you use arr=arr.flatten()
to make it 1-D**

In [ ]:
#Error
arr=np.array([[1,2,3],[23,8,9]])
print(np.random.choice(arr, 10))

ValueError: ignored

In [ ]:
arr=arr.flatten()
print(np.random.choice(arr, 10))

[ 9  2  3  1 23  2 23  9 23  9]


shuffle an array in place

In [ ]:
arr = np.array(range(10))#(shuffle)  random ديه معناها انه بيفنط الارقام بطريقه
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
np.random.shuffle(arr)
print(arr)

[0 2 4 9 6 7 8 1 5 3]


**generate a permutation of an array**

In [ ]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [3 7 0 4 9 2 6 8 5 1]


**compute the indices of the min and max along a specified axis**

In [ ]:
arr = np.random.rand(5,5)

In [ ]:
# along the row
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))

[0 0 2 0 0]
[1 1 3 3 2]


In [ ]:
# along the column
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[1 2 2 1 2]
[0 4 4 3 0]


In [ ]:
print(np.argmin(arr))
print(np.argmax(arr))

12
14


#**Slicing & Indexing**

In [ ]:
arr = np.array(range(100))#1-D array
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
arr = np.array(range(25)).reshape((5,5))
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
print(arr[4][4])
# or more concisely
print(arr[4,4])

24
24


indexing with slicing

In [ ]:
print(arr[0:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
print(arr[0:2,0:4])

[[0 1 2 3]
 [5 6 7 8]]


In [ ]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(2,2,2,2)
print(arr)
print("-----------------")
# equivalent to arr[0,:,:,:]
print(arr[0, 1,...])    

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
-----------------
[[4 5]
 [6 7]]


boolean indexing

In [ ]:
arr1 = np.arange(25).reshape((5,5))
print(arr1)
print('\n')
bools = np.array([True, True, False, True, False])
print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [ ]:
# negate the condition
print(arr1[~bools])  


[[10 11 12 13 14]
 [20 21 22 23 24]]


In [ ]:
arr2 = np.array([1,2,3,4,5])
# multiple conditions
print(arr1[(arr2<2) | (arr2>4)])  

[[ 0  1  2  3  4]
 [20 21 22 23 24]]


dimension inference

In [ ]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(25)).reshape((5,-1))
arr2=np.array(range(25)).reshape(5,5)
print(arr2.shape)
print(arr.shape)

(5, 5)
(5, 5)


**find elements/indices by conditions**

In [ ]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [ ]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, 1, 0))
arr2=np.where(arr>5, 1, 0)
print("\n")
# find the indices of the elements on conditions
print(np.argwhere(arr2==0))

[[0 0 0 0]
 [0 0 1 1]
 [1 1 1 1]
 [1 1 1 1]]


[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [1 0]
 [1 1]]


#**Manipulate an Array**

**The numpy.ravel()**

functions returns contiguous flattened array(1D array with all the input-array elements and with the same type as it). A copy is made only if needed.

In [ ]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
arr.ravel()#مش فهماها اوي الصراحه حساها زي ال flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

change the shape of an array

In [ ]:
arr = np.random.rand(3,4)

In [ ]:
# change the shape of an array and return a copy
arr.reshape((2,6))

array([[0.41051979, 0.19100696, 0.96749431, 0.65075037, 0.86545985,
        0.02524236],
       [0.26690581, 0.5020711 , 0.06744864, 0.99303326, 0.2364624 ,
        0.37429218]])

In [ ]:
# change the shape of an array in place
arr.resize((2,6))

**append elements to an array**

In [ ]:
arr = np.array([1,2,3])
arr1 = np.append(arr, 4)    
print(arr1)


[1 2 3 4]


In [ ]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


 insert elements into an array

In [ ]:
# np.insert(array, position, element)
# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [1,2,3])    
print(arr3)

[100   1   2   3]
[1 2 3 1 2 3]


delete elements from an array

In [ ]:
#arr=[1,2,3]
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [ ]:
#arr=[1,2,3]
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


copy an array

In [ ]:
# the following methods are all deep copy
#In case of deep copy, 
#a copy of object is copied in other object.
#It means that any changes made to a copy of object do not reflect in the original object. 
arr1 = np.copy(arr)
# or 
arr1 = arr.copy()
# or 
arr1 = np.array(arr, copy=True)

**swap axes**

In [ ]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)
print(arr1.shape)

print('\n ------------------------')

A=arr1.swapaxes(1,2)
print(A)
print(A.shape)


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
(2, 2, 4)

 ------------------------
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]
(2, 4, 2)


transpose of a high dimensional array with specified order of axes

In [ ]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)
print('\n ------------------------')
arr1.transpose((1,0,2))


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]

 ------------------------


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [ ]:
arr1.transpose((2,1,0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

#**Combine & Split an Array**

In [ ]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [ ]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [ ]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [ ]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)
print("\n--------------------")
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]

--------------------
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [ ]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

print("\n--------------------")

# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]

--------------------
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


**split an array** 

In [ ]:
arr = np.random.rand(4,4)
arr

array([[0.36571913, 0.53388598, 0.16201584, 0.59743311],
       [0.29315247, 0.63205049, 0.02619661, 0.88759346],
       [0.01611863, 0.12695803, 0.77716246, 0.04589523],
       [0.71099869, 0.97104614, 0.87168293, 0.71016165]])

In [ ]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr,2)
print(arr1)

[array([[0.36571913, 0.53388598, 0.16201584, 0.59743311],
       [0.29315247, 0.63205049, 0.02619661, 0.88759346]]), array([[0.01611863, 0.12695803, 0.77716246, 0.04589523],
       [0.71099869, 0.97104614, 0.87168293, 0.71016165]])]


In [ ]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr,2)
print(arr2)

[array([[0.36571913, 0.53388598],
       [0.29315247, 0.63205049],
       [0.01611863, 0.12695803],
       [0.71099869, 0.97104614]]), array([[0.16201584, 0.59743311],
       [0.02619661, 0.88759346],
       [0.77716246, 0.04589523],
       [0.87168293, 0.71016165]])]


#**Set operation**

select the unique elements from an array

In [ ]:
arr = np.array([1,1,2,2,3,3,4,5,6])
print(np.unique(arr))

[1 2 3 4 5 6]


In [ ]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


compute the intersection & union of two arrays

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [ ]:
# intersection
print(np.intersect1d(arr1, arr2))

[3 4 5]


In [ ]:
# union
print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


compute whether each element of an array is contained in another

In [ ]:
print(np.in1d(arr1, arr2))

[False False  True  True  True]


compute the elements in an array that are not in another

In [ ]:
print(np.setdiff1d(arr1, arr2))# arr2 و مش في arr1 بجيب الحاجات الي موجوده ف 

[1 2]


compute the elements in either of two arrays, but not both

In [ ]:
print(np.setxor1d(arr1, arr2))#بعد ما جبت الحاجات الي مش موجوده ف الarr1و arr2 و بعملهم union 

[1 2 6 7]
